In [1]:
import numpy as np
import pandas as pd

In [2]:
movies=pd.read_csv('tmdb_5000_movies.csv.zip')
credits=pd.read_csv('tmdb_5000_credits.csv.zip')

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)['cast'].values

<StringArray>
['[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 2, "id": 59231, "name": "Joel David Moore", "order": 6}, {"cast_id": 9, "character": "Moat", "credit_id": "52fe48009251416c750ac9e5", "gender": 1, "id": 30485, "name": "CCH Pounder", "order": 7}, {"cast_id": 11, "character": "Eytukan", "credit_id": "52fe48009251416c750ac9ed", "gender": 2, "id": 15853, "name": "Wes Studi", "order": 8}, {"cast_id": 10, "character": "Tsu'Tey", "credit_id": "52fe48009251416c750ac9e9", "gender": 2, "id": 10964, "name": "Laz Alonso", "order": 9}, {"cast_id": 12, "character": "Dr. Max Patel", "credit_id": "52fe48009251416c750ac9f1", "gender": 2, "id": 95697, "name": "Dileep Rao", "order": 10}, {"cast_id": 13, "character": "Lyle Wainfleet", "credit_id": "52fe48009251416c750ac9f5", "gender": 2, "id": 98215, "name": "Matt Gerald", "order": 11}, {"cast_id": 32, "character": "Private Fike", "credit_id": "52fe48009251416c750aca5b", "gender": 2, "id": 154153, "name": "Sean Anthony Moran", "order": 12}, {"cast_id": 33, "character": "Cryo Vault Med Tech", "credit_id": "52fe48009251416c750aca5f", "gender": 2, "id": 397312, "name": "Jason Whyte", "order": 13}, {"cast_id": 34, "character": "Venture Star Crew Chief", "credit_id": "52fe48009251416c750aca63", "gender": 2, "id": 42317, "name": "Scott Lawrence", "order": 14}, {"cast_id": 35, "character": "Lock Up Trooper", "credit_id": "52fe48009251416c750aca67", "gender": 2, "id": 986734, "name": "Kelly Kilgour", "order": 15}, {"cast_id": 36, "character": "Shuttle Pilot", "credit_id": "52fe48009251416c750aca6b", "gender": 0, "id": 1207227, "name": "James Patrick Pitt", "order": 16}, {"cast_id": 37, "character": "Shuttle Co-Pilot", "credit_id": "52fe48009251416c750aca6f", "gender": 0, "id": 1180936, "name": "Sean Patrick Murphy", "order": 17}, {"cast_id": 38, "character": "Shuttle Crew Chief", "credit_id": "52fe48009251416c750aca73", "gender": 2, "id": 1019578, "name": "Peter Dillon", "order": 18}, {"cast_id": 39, "character": "Tractor Operator / Troupe", "credit_id": "52fe48009251416c750aca77", "gender": 0, "id": 91443, "name": "Kevin Dorman", "order": 19}, {"cast_id": 40, "character": "Dragon Gunship Pilot", "credit_id": "52fe48009251416c750aca7b", "gender": 2, "id": 173391, "name": "Kelson Henderson", "order": 20}, {"cast_id": 41, "character": "Dragon Gunship Gunner", "credit_id": "52fe48009251416c750aca7f", "gender": 0, "id": 1207236, "name": "David Van Horn", "order": 21}, {"cast_id": 42, "character": "Dragon Gunship Navigator", "credit_id": "52fe48009251416c750aca83", "gender": 0, "id": 215913, "name": "Jacob Tomuri", "order": 22}, {"cast_id": 43, "character": "Suit #1", "credit_id": "52fe48009251416c750aca87", "gender": 0, "id": 143206, "name": "Michael Blain-Rozgay", "order": 23}, {"cast_id": 44, "character": "Suit #2", "credit_id": "52fe48009251416c750aca8b", "gender": 2, "id": 169676, "name": "Jon Curry", "order": 24}, {"cast_id": 46, "character": "Ambient Room Tech", "credit_id": "52fe48009251416c750aca8f", "gender": 0, "id": 1048610, "name": "Luke Hawker", "order": 25}, {"cast_id": 47, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48009251416c750aca93", "gender": 0, "id": 42288, "name": "Woody Schultz", "order": 26}, {"cast_id": 48, "character": "Horse Clan Leader", "credit_id": "52fe48009251416c750aca97", "gender": 2, "id": 68278, "name": "Peter Mensah", "order": 27}, {"cast_id": 49, "character": "Link Room Tech", "credit_id": "52fe48009251416c750aca9b", "gender": 0, "id": 1207247, "name": "Sonia Yee", "order": 28}, {"cast_id": 50, "character": "Basketball Avatar / Troupe", "credit_id": "52fe48009251416c750aca9f", "gender": 1, "id": 1207248, "name": "Jahnel Curfman", "order": 29}, {"cast_id": 51, "character": "Basketball Avatar", "credit_id": "52fe48009251416c750acaa3", "gender": 0, "id": 89714, "name": "Ilram Choi", "order": 30}, {"cast_id": 52, "character": "Na'vi Child", "credit_id": "52fe48009251416c750acaa7", "gender": 0, "id": 1207249, "name": "Kyla Warren", "order": 31}, {"cast_id": 53, "character": "Troupe", "credit_id": "52fe48009251416c750acaab", "gender": 0, "id": 1207250, "name": "Lisa Roumain", "order": 32}, {"cast_id": 54, "character": "Troupe", "credit_id": "52fe48009251416c750acaaf", "gender": 1, "id": 83105, "name": "Debra Wilson", "order": 33}, {"cast_id": 57, "character": "Troupe", "credit_id": "52fe48009251416c750acabb", "gender": 0, "id": 1207253, "name": "Chris Mala", "order": 34}, {"cast_id": 55, "character": "Troupe", "credit_id": "52fe48009251416c750acab3", "gender": 0, "id": 1207251, "name": "Taylor Kibby", "order": 35}, {"cast_id": 56, "character": "Troupe", "credit_id": "52fe48009251416c750acab7", "gender": 0, "id": 1207252, "name": "Jodie Landau", "order": 36}, {"cast_id": 58, "character": "Troupe", "credit_id": "52fe48009251416c750acabf", "gender": 0, "id": 1207254, "name": "Julie Lamm", "order": 37}, {"cast_id": 59, "character": "Troupe", "credit_id": "52fe48009251416c750acac3", "gender": 0, "id": 1207257, "name": "Cullen B. Madden", "order": 38}, {"cast_id": 60, "character": "Troupe", "credit_id": "52fe48009251416c750acac7", "gender": 0, "id": 1207259, "name": "Joseph Brady Madden", "order": 39}, {"cast_id": 61, "character": "Troupe", "credit_id": "52fe48009251416c750acacb", "gender": 0, "id": 1207262, "name": "Frankie Torres", "order": 40}, {"cast_id": 62, "character": "Troupe", "credit_id": "52fe48009251416c750acacf", "gender": 1, "id": 1158600, "name": "Austin Wilson", "order": 41}, {"cast_id": 63, "character": "Troupe", "credit_id": "52fe48019251416c750acad3", "gender": 1, "id": 983705, "name": "Sara Wilson", "order": 42}, {"cast_id": 64, "character": "Troupe", "credit_id": "52fe48019251416c750acad7", "gender": 0, "id": 1207263, "name": "Tamica Washington-Miller", "order": 43}, {"cast_id": 65, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadb", "gender": 1, "id": 1145098, "name": "Lucy Briant", "order": 44}, {"cast_id": 66, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acadf", "gender": 2, "id": 33305, "name": "Nathan Meister", "order": 45}, {"cast_id": 67, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae3", "gender": 0, "id": 1207264, "name": "Gerry Blair", "order": 46}, {"cast_id": 68, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acae7", "gender": 2, "id": 33311, "name": "Matthew Chamberlain", "order": 47}, {"cast_id": 69, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaeb", "gender": 0, "id": 1207265, "name": "Paul Yates", "order": 48}, {"cast_id": 70, "character": "Op Center Duty Officer", "credit_id": "52fe48019251416c750acaef", "gender": 0, "id": 1207266, "name": "Wray Wilson", "order": 49}, {"cast_id": 71, "character": "Op Center Staff", "credit_id": "52fe48019251416c750acaf3", "gender": 2, "id": 54492, "name": "James Gaylyn", "order": 50}, {"cast_id": 72, "character": "Dancer", "credit_id": "52fe48019251416c750acaf7", "gender": 0, "id": 1207267, "name": "Melvin Leno Clark III", "order": 51}, {"cast_id": 73, "character": "Dancer", "credit_id": "52fe48019251416c750acafb", "gender": 0, "id": 1207268, "name": "Carvon Futrell", "order": 52}, {"cast_id": 74, "character": "Dancer", "credit_id": "52fe48019251416c750acaff", "gender": 0, "id": 1207269, "name": "Brandon Jelkes", "order": 53}, {"cast_id": 75, "character": "Dancer", "credit_id": "52fe48019251416c750acb03", "gender": 0, "id": 1207270, "name": "Micah Moch", "order": 54}, {"cast_id": 76, "character": "Dancer", "credit_id": "52fe48019251416c750acb07", "gender": 0, "id": 1207271, "name": "Hanniyah Muhammad", "order": 55}, {"cast_id": 77, "character": "Dancer", "credit_id": "52fe48019251416c750acb0b", "gender": 0, "id": 1207272, "name": "Christopher Nolen", "order": 56}, {"cast_id": 78, "character": "Dancer", "credit_id": "52fe48019251416c750acb0f", "gender": 0, "id": 1207273, "name": "Christa Oliver", "order": 57}, {"cast_id": 79, "character": "Dancer", "credit_id": "52fe48019251416c750acb13", "gender": 0, "id": 1207274, "name": "April Marie Thomas", "order": 58}, {"cast_id": 80, "character": "Dancer", "credit_id": "52fe48019251416c750acb17", "gender": 0, "id": 1207275, "name": "Bravita A. Threatt", "order": 59}, {"cast_id": 81, "character": "Mining Chief (uncredited)", "credit_id": "52fe48019251416c750acb1b", "gender": 0, "id": 1207276, "name": "Colin Bleasdale", "order": 60}, {"cast_id": 82, "character": "Veteran Miner (uncredited)", "credit_id": "52fe48019251416c750acb1f", "gender": 0, "id": 107969, "name": "Mike Bodnar", "order": 61}, {"cast_id": 83, "character": "Richard (uncredited)", "credit_id": "52fe48019251416c750acb23", "gender": 0, "id": 1207278, "name": "Matt Clayton", "order": 62}, {"cast_id": 84, "character": "Nav'i (uncredited)", "credit_id": "52fe48019251416c750acb27", "gender": 1, "id": 147898, "name": "Nicole Dionne", "order": 63}, {"cast_id": 85, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2b", "gender": 0, "id": 1207280, "name": "Jamie Harrison", "order": 64}, {"cast_id": 86, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb2f", "gender": 0, "id": 1207281, "name": "Allan Henry", "order": 65}, {"cast_id": 87, "character": "Ground Technician (uncredited)", "credit_id": "52fe48019251416c750acb33", "gender": 2, "id": 1207282, "name": "Anthony Ingruber", "order": 66}, {"cast_id": 88, "character": "Flight Crew Mechanic (uncredited)", "credit_id": "52fe48019251416c750acb37", "gender": 0, "id": 1207283, "name": "Ashley Jeffery", "order": 67}, {"cast_id": 14, "character": "Samson Pilot", "credit_id": "52fe48009251416c750ac9f9", "gender": 0, "id": 98216, "name": "Dean Knowsley", "order": 68}, {"cast_id": 89, "character": "Trooper (uncredited)", "credit_id": "52fe48019251416c750acb3b", "gender": 0, "id": 1201399, "name": "Joseph Mika-Hunt", "order": 69}, {"cast_id": 90, "character": "Banshee (uncredited)", "credit_id": "52fe48019251416c750acb3f", "gender": 0, "id": 236696, "name": "Terry Notary", "order": 70}, {"cast_id": 91, "character": "Soldier (uncredited)", "credit_id": "52fe48019251416c750acb43", "gender": 0, "id": 1207287, "name": "Kai Pantano", "order": 71}, {"cast_id": 92, "character": "Blast Technician (uncredited)", "credit_id": "52fe48019251416c750acb47", "gender": 0, "id": 1207288, "name": "Logan Pithyou", "order": 72}, {"cast_id": 93, "character": "Vindum Raah (uncredited)", "credit_id": "52fe48019251416c750acb4b", "gender": 0, "id": 1207289, "name": "Stuart Pollock", "order": 73}, {"cast_id": 94, "character": "Hero (uncredited)", "credit_id": "52fe48019251416c750acb4f", "gender": 0, "id": 584868, "name": "Raja", "order": 74}, {"cast_id": 95, "character": "Ops Centreworker (uncredited)", "credit_id": "52fe48019251416c750acb53", "gender": 0, "id": 1207290, "name": "Gareth Ruck", "order": 75}, {"cast_id": 96, "character": "Engineer (uncredited)", "credit_id": "52fe48019251416c750acb57", "gender": 0, "id": 1062463, "name": "Rhian Sheehan", "order": 76}, {"cast_id": 97, "character": "Col. Quaritch's Mech Suit (uncredited)", "credit_id": "52fe48019251416c750acb5b", "gender": 0, "id": 60656, "name": "T. J. Storm", "order": 77}, {"cast_id": 98, "character": "Female Marine (uncredited)", "credit_id": "52fe48019251416c750acb5f", "gender": 0, "id": 1207291, "name": "Jodie Taylor", "order": 78}, {"cast_id": 99, "character": "Ikran Clan Leader (uncredited)", "credit_id": "52fe48019251416c750acb63", "gender": 1, "id": 1186027, "name": "Alicia Vela-Bailey", "order": 79}, {"cast_id": 100, "character": "Geologist (uncredited)", "credit_id": "52fe48019251416c750acb67", "gender": 0, "id": 1207292, "name": "Richard Whiteside", "order": 80}, {"cast_id": 101, "character": "Na'vi (uncredited)", "credit_id": "52fe48019251416c750acb6b", "gender": 0, "id": 103259, "name": "Nikie Zambo", "order": 81}, {"cast_id": 102, "character": "Ambient Room Tech / Troupe", "credit_id": "52fe48019251416c750acb6f", "gender": 1, "id": 42286, "name": "Julene Renee", "order": 82}]']
Length: 1, dtype: str

In [5]:
movies=movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
movies['original_language'].value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ar       2
id       2
ro       2
te       1
xx       1
hu       1
is       1
tr       1
nb       1
af       1
pl       1
vi       1
ky       1
no       1
sl       1
ps       1
el       1
Name: count, dtype: int64

In [8]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   str
 2   homepage              1713 non-null   str
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   str
 5   original_language     4809 non-null   str
 6   original_title        4809 non-null   str
 7   overview              4806 non-null   str
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   str
 10  production_countries  4809 non-null   str
 11  release_date          4808 non-null   str
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   str
 15  status                4809 non-null   str
 16  tagline               3965 non-null   str
 17  title                 4809 non-null   str
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   str
 22  crew                  4809 non-null   str
dtypes: float64(3), int64(5), str(15)
memory usage: 864.2 KB

In [9]:
movies=movies[['movie_id','title','overview','genres','keywords', 'cast', 'crew']]

In [10]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace=True)

In [13]:
movies.duplicated().sum()

np.int64(0)

In [14]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
def convert(obj):
   L=[]
   for i in ast.literal_eval(obj):
       L.append(i['name'])
   return L

In [16]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [17]:
movies['genres']=movies['genres'].apply(convert)

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords']=movies['keywords'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
def convert3(obj):
    L = []
    counter = 0

    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break

    return L

In [22]:
movies['cast']=movies['cast'].apply(convert3)

In [23]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [24]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [25]:
def fetch_director(obj):
    L = []
    counter = 0

    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            L.append(i['name'])
            break

    return L

In [26]:
movies['crew']=movies['crew'].apply(fetch_director)

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [29]:
movies['overview']=movies['overview'].apply(lambda x: x.split())

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:

movies['genres'] = movies['genres'].apply(lambda x: [i.lower() for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.lower() for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.lower() for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.lower() for i in x])

In [32]:
movies.iloc[0]

movie_id                                                19995
title                                                  Avatar
overview    [In, the, 22nd, century,, a, paraplegic, Marin...
genres          [action, adventure, fantasy, science fiction]
keywords    [culture clash, future, space war, space colon...
cast         [sam worthington, zoe saldana, sigourney weaver]
crew                                          [james cameron]
Name: 0, dtype: object

In [33]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colon...","[sam worthington, zoe saldana, sigourney weaver]",[james cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ...","[johnny depp, orlando bloom, keira knightley]",[gore verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi...","[daniel craig, christoph waltz, léa seydoux]",[sam mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret i...","[christian bale, michael caine, gary oldman]",[christopher nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[action, adventure, science fiction]","[based on novel, mars, medallion, space travel...","[taylor kitsch, lynn collins, samantha morton]",[andrew stanton]

In [34]:
movies['tags']=movies['overview']+movies['keywords']+movies['genres']+movies['cast']+movies['crew']

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colon...","[sam worthington, zoe saldana, sigourney weaver]",[james cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india ...","[johnny depp, orlando bloom, keira knightley]",[gore verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi...","[daniel craig, christoph waltz, léa seydoux]",[sam mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret i...","[christian bale, michael caine, gary oldman]",[christopher nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[action, adventure, science fiction]","[based on novel, mars, medallion, space travel...","[taylor kitsch, lynn collins, samantha morton]",[andrew stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [36]:
new_df=movies[['movie_id','title','tags']]

In [37]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [38]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [39]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [40]:
!pip install nltk

Requirement already satisfied: nltk in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (3.10.2)
Requirement already satisfied: defusedxml in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: colorama in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (from click->nltk) (0.4.6)

In [41]:
import nltk

In [42]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [43]:
def stem(text):
    y=[]
    for i in text.split():
        ps.stem(i)

In [44]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [45]:
movies.loc[0, 'overview']
movies.loc[0, 'keywords']
movies.loc[0, 'genres']
movies.loc[0, 'cast']
movies.loc[0, 'crew']

['james cameron']

In [46]:
movies.loc[0, 'tags']

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d',
 'action',
 'adventure',
 'fantasy',
 'science fiction',
 'sam worthington',
 'zoe saldana',
 'sigourney weaver',
 'james cameron']

In [47]:
new_df[['title', 'tags']].head()

,title,tags
0,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,Spectre,a cryptic message from bond’s past sends him o...
3,The Dark Knight Rises,following the death of district attorney harve...
4,John Carter,"john carter is a war-weary, former military ca..."

In [48]:
new_df['tags'][1]

"captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. ocean drug abuse exotic island east india trading company love of one's life traitor shipwreck strong woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger adventure fantasy action johnny depp orlando bloom keira knightley gore verbinski"

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000,stop_words='english')

In [50]:
cv.fit_transform(new_df['tags']).toarray().shape

(4806, 5000)

In [51]:
vectors=cv.fit_transform(new_df['tags']).toarray()

In [52]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [53]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [54]:
 cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'],
      shape=(5000,), dtype=object)

In [55]:
len(cv.get_feature_names_out())

5000

In [56]:
['loved','loving','love']
['love','love','love']

['love', 'love', 'love']

In [57]:
ps.stem('loved')

'love'

In [58]:
ps.stem('dance')

'danc'

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

In [60]:
cosine_similarity(vectors)

array([[1.        , 0.06885304, 0.04948717, ..., 0.03142697, 0.05345225,
        0.        ],
       [0.06885304, 1.        , 0.04259177, ..., 0.04057204, 0.        ,
        0.        ],
       [0.04948717, 0.04259177, 1.        , ..., 0.01944039, 0.08817334,
        0.        ],
       ...,
       [0.03142697, 0.04057204, 0.01944039, ..., 1.        , 0.06299408,
        0.03276488],
       [0.05345225, 0.        , 0.08817334, ..., 0.06299408, 1.        ,
        0.03715188],
       [0.        , 0.        , 0.        , ..., 0.03276488, 0.03715188,
        1.        ]], shape=(4806, 4806))

In [61]:
cosine_similarity(vectors).shape

(4806, 4806)

In [62]:
similarity=cosine_similarity(vectors)

In [63]:
new_df[new_df['title'] == 'Avatar']

   movie_id   title                                               tags
0     19995  Avatar  in the 22nd century, a paraplegic marine is di...

In [64]:
list(enumerate(similarity[0]))

[(0, np.float64(0.9999999999999997)),
 (1, np.float64(0.06885303726590962)),
 (2, np.float64(0.04948716593053934)),
 (3, np.float64(0.022645540682891912)),
 (4, np.float64(0.30806161848616215)),
 (5, np.float64(0.15032920560056579)),
 (6, np.float64(0.023570226039551584)),
 (7, np.float64(0.13093073414159542)),
 (8, np.float64(0.04020151261036848)),
 (9, np.float64(0.07516460280028289)),
 (10, np.float64(0.10444659357341869)),
 (11, np.float64(0.06810052246069988)),
 (12, np.float64(0.055470019622522904)),
 (13, np.float64(0.02684624220856097)),
 (14, np.float64(0.1281025230440697)),
 (15, np.float64(0.04399413450640598)),
 (16, np.float64(0.10434983894999016)),
 (17, np.float64(0.11120768749710652)),
 (18, np.float64(0.12701705922171763)),
 (19, np.float64(0.07053456158585981)),
 (20, np.float64(0.03380617018914066)),
 (21, np.float64(0.050529115263991134)),
 (22, np.float64(0.04364357804719846)),
 (23, np.float64(0.055470019622522904)),
 (24, np.float64(0.04548588261473419)),
 (25, np.float64(0.0669774686623137)),
 (26, np.float64(0.17126976771553504)),
 (27, np.float64(0.1963961012123931)),
 (28, np.float64(0.07106690545187014)),
 (29, np.float64(0.05642764926868785)),
 (30, np.float64(0.08870655251454873)),
 (31, np.float64(0.14907119849998593)),
 (32, np.float64(0.06666666666666665)),
 (33, np.float64(0.07807200583588264)),
 (34, np.float64(0.0)),
 (35, np.float64(0.1811643254631353)),
 (36, np.float64(0.16495721976846447)),
 (37, np.float64(0.08703882797784891)),
 (38, np.float64(0.03897418814769785)),
 (39, np.float64(0.09701425001453318)),
 (40, np.float64(0.03265986323710904)),
 (41, np.float64(0.18039504672067896)),
 (42, np.float64(0.0)),
 (43, np.float64(0.09097176522946838)),
 (44, np.float64(0.04020151261036848)),
 (45, np.float64(0.07001400420140047)),
 (46, np.float64(0.18856180831641262)),
 (47, np.float64(0.31972210155418135)),
 (48, np.float64(0.08944271909999156)),
 (49, np.float64(0.03903600291794132)),
 (50, np.float64(0.07396002616336388)),
 (51, np.float64(0.08926073982886733)),
 (52, np.float64(0.24743582965269667)),
 (53, np.float64(0.11925695879998875)),
 (54, np.float64(0.020412414523193145)),
 (55, np.float64(0.048686449556014755)),
 (56, np.float64(0.24886840673530203)),
 (57, np.float64(0.07126966450997983)),
 (58, np.float64(0.0305887645160749)),
 (59, np.float64(0.05954913341754135)),
 (60, np.float64(0.015032920560056577)),
 (61, np.float64(0.23190036174568107)),
 (62, np.float64(0.048154341234307674)),
 (63, np.float64(0.06950480468569158)),
 (64, np.float64(0.04898979485566356)),
 (65, np.float64(0.033333333333333326)),
 (66, np.float64(0.015430334996209188)),
 (67, np.float64(0.20083160441856085)),
 (68, np.float64(0.07930515857181442)),
 (69, np.float64(0.04642070825485275)),
 (70, np.float64(0.12780193008453872)),
 (71, np.float64(0.06963106238227913)),
 (72, np.float64(0.11790126894931265)),
 (73, np.float64(0.019802950859533482)),
 (74, np.float64(0.25980762113533157)),
 (75, np.float64(0.07492686492653551)),
 (76, np.float64(0.06666666666666667)),
 (77, np.float64(0.019730544946679602)),
 (78, np.float64(0.031139957766460915)),
 (79, np.float64(0.07516460280028289)),
 (80, np.float64(0.01924500897298752)),
 (81, np.float64(0.0812362394459923)),
 (82, np.float64(0.08421519210665189)),
 (83, np.float64(0.23791547571544325)),
 (84, np.float64(0.08767140075192091)),
 (85, np.float64(0.07258661863112975)),
 (86, np.float64(0.09128709291752767)),
 (87, np.float64(0.17407765595569782)),
 (88, np.float64(0.047583095143088644)),
 (89, np.float64(0.04914731871829904)),
 (90, np.float64(0.03698001308168194)),
 (91, np.float64(0.20604887854797269)),
 (92, np.float64(0.04548588261473419)),
 (93, np.float64(0.04548588261473419)),
 (94, np.float64(0.2809757434745082)),
 (95, np.float64(0.25560386016907743)),
 (96, np.float64(0.07396002616336388)),
 (97, np.float64(0.07930515857181442)),
 (98, np.float64(0.05345224838248487)),
 (99, np.float64(0.01601281538050871)),
 (100, np.float64(0.07071067811865475)),
 (101, np.float64(0.14907119849998593)),
 (102, np.float64(0.11731769201708261)),
 (103, np.float64(0.08660254037844387)),
 (104, np.float64(0.031722063428725765)),
 (105, np.float64(0.09128709291752767)),
 (106, np.float64(0.03999999999999999)),
 (107, np.float64(0.10527227119356301)),
 (108, np.float64(0.17320508075688773)),
 (109, np.float64(0.06221710168382551)),
 (110, np.float64(0.12890067732709792)),
 (111, np.float64(0.1825741858350553)),
 (112, np.float64(0.08804509063256238)),
 (113, np.float64(0.031139957766460915)),
 (114, np.float64(0.030065841120113155)),
 (115, np.float64(0.06405126152203484)),
 (116, np.float64(0.050529115263991134)),
 (117, np.float64(0.0305887645160749)),
 (118, np.float64(0.010497277621629558)),
 (119, np.float64(0.058621038176054914)),
 (120, np.float64(0.0)),
 (121, np.float64(0.056949479745149925)),
 (122, np.float64(0.07921180343813393)),
 (123, np.float64(0.10079052613579391)),
 (124, np.float64(0.07332355751067664)),
 (125, np.float64(0.07779466213221042)),
 (126, np.float64(0.061721339984836754)),
 (127, np.float64(0.13617658132983804)),
 (128, np.float64(0.01951800145897066)),
 (129, np.float64(0.08660254037844385)),
 (130, np.float64(0.015161960871578064)),
 (131, np.float64(0.09128709291752767)),
 (132, np.float64(0.04296689244236597)),
 (133, np.float64(0.04948716593053934)),
 (134, np.float64(0.07807200583588264)),
 (135, np.float64(0.0)),
 (136, np.float64(0.01571348402636772)),
 (137, np.float64(0.022645540682891912)),
 (138, np.float64(0.08908708063747478)),
 (139, np.float64(0.0699854212223765)),
 (140, np.float64(0.04296689244236597)),
 (141, np.float64(0.1951800145897066)),
 (142, np.float64(0.0547722557505166)),
 (143, np.float64(0.06804138174397717)),
 (144, np.float64(0.06375767130633381)),
 (145, np.float64(0.08292884288627292)),
 (146, np.float64(0.034299717028501764)),
 (147, np.float64(0.1)),
 (148, np.float64(0.05855400437691198)),
 (149, np.float64(0.3077287274483318)),
 (150, np.float64(0.24377011365784199)),
 (151, np.float64(0.0962250448649376)),
 (152, np.float64(0.036514837167011066)),
 (153, np.float64(0.05443310539518173)),
 (154, np.float64(0.01951800145897066)),
 (155, np.float64(0.013333333333333329)),
 (156, np.float64(0.15701620314577236)),
 (157, np.float64(0.06324555320336757)),
 (158, np.float64(0.32005290567945544)),
 (159, np.float64(0.05855400437691198)),
 (160, np.float64(0.05802588531856594)),
 (161, np.float64(0.06221710168382551)),
 (162, np.float64(0.06221710168382551)),
 (163, np.float64(0.07273929674533078)),
 (164, np.float64(0.05694947974514993)),
 (165, np.float64(0.059628479399994376)),
 (166, np.float64(0.0975900072948533)),
 (167, np.float64(0.04364357804719846)),
 (168, np.float64(0.16666666666666666)),
 (169, np.float64(0.13787639750914224)),
 (170, np.float64(0.07273929674533078)),
 (171, np.float64(0.055470019622522904)),
 (172, np.float64(0.08333333333333334)),
 (173, np.float64(0.01632993161855452)),
 (174, np.float64(0.1026529805149473)),
 (175, np.float64(0.030065841120113155)),
 (176, np.float64(0.014433756729740642)),
 (177, np.float64(0.024077170617153837)),
 (178, np.float64(0.016495721976846445)),
 (179, np.float64(0.04618802153517006)),
 (180, np.float64(0.014106912317171963)),
 (181, np.float64(0.013245323570650435)),
 (182, np.float64(0.07580980435789032)),
 (183, np.float64(0.059234887775909226)),
 (184, np.float64(0.3007682470965618)),
 (185, np.float64(0.09897433186107867)),
 (186, np.float64(0.034299717028501764)),
 (187, np.float64(0.08804509063256237)),
 (188, np.float64(0.05196558419693047)),
 (189, np.float64(0.049236596391733084)),
 (190, np.float64(0.06337242505244778)),
 (191, np.float64(0.045098761680169734)),
 (192, np.float64(0.05773502691896257)),
 (193, np.float64(0.07161148740394328)),
 (194, np.float64(0.015861031714362882)),
 (195, np.float64(0.03606678538669729)),
 (196, np.float64(0.08703882797784891)),
 (197, np.float64(0.04472135954999578)),
 (198, np.float64(0.033686076842660756)),
 (199, np.float64(0.07999999999999999)),
 (200, np.float64(0.14985372985307102)),
 (201, np.float64(0.019802950859533482)),
 (202, np.float64(0.019802950859533482)),
 (203, np.float64(0.08703882797784891)),
 (204, np.float64(0.014907119849998594)),
 (205, np.float64(0.039605901719066965)),
 (206, np.float64(0.1128552985373757)),
 (207, np.float64(0.1352962850405092)),
 (208, np.float64(0.15491933384829665)),
 (209, np.float64(0.017817416127494958)),
 (210, np.float64(0.029329423004270654)),
 (211, np.float64(0.047583095143088644)),
 (212, np.float64(0.05100613704506705)),
 (213, np.float64(0.061199006136210446)),
 (214, np.float64(0.01571348402636772)),
 (215, np.float64(0.10811798054391773)),
 (216, np.float64(0.03796631983009995)),
 (217, np.float64(0.06851887098275315)),
 (218, np.float64(0.02581988897471611)),
 (219, np.float64(0.05855400437691198)),
 (220, np.float64(0.13770607453181924)),
 (221, np.float64(0.01601281538050871)),
 (222, np.float64(0.17106744068953988)),
 (223, np.float64(0.15322617553657472)),
 (224, np.float64(0.05560384374855326)),
 (225, np.float64(0.04803844614152614)),
 (226, np.float64(0.07213357077339458)),
 (227, np.float64(0.08333333333333333)),
 (228, np.float64(0.22636658336724408)),
 (229, np.float64(0.136176581329838)),
 (230, np.float64(0.1986798535597565)),
 (231, np.float64(0.02909571869813231)),
 (232, np.float64(0.14426714154678916)),
 (233, np.float64(0.17457431218879385)),
 (234, np.float64(0.04026936331284146)),
 (235, np.float64(0.036514837167011066)),
 (236, np.float64(0.19882696935448685)),
 (237, np.float64(0.03903600291794132)),
 (238, np.float64(0.09903751369442765)),
 (239, np.float64(0.3079201435678004)),
 (240, np.float64(0.0305887645160749)),
 (241, np.float64(0.05345224838248487)),
 (242, np.float64(0.06467616667635545)),
 (243, np.float64(0.06711560552140243)),
 (244, np.float64(0.03442651863295481)),
 (245, np.float64(0.04399413450640598)),
 (246, np.float64(0.09152086306448586)),
 (247, np.float64(0.0)),
 (248, np.float64(0.027029495135979433)),
 (249, np.float64(0.15009575487729127)),
 (250, np.float64(0.0)),
 (251, np.float64(0.07223151185146151)),
 (252, np.float64(0.012379689211803456)),
 (253, np.float64(0.10596258856520348)),
 (254, np.float64(0.04898979485566356)),
 (255, np.float64(0.0)),
 (256, np.float64(0.09901475429766741)),
 (257, np.float64(0.060647843486312254)),
 (258, np.float64(0.029329423004270654)),
 (259, np.float64(0.03265986323710904)),
 (260, np.float64(0.28323527714997326)),
 (261, np.float64(0.04296689244236597)),
 (262, np.float64(0.04850712500726659)),
 (263, np.float64(0.05855400437691198)),
 (264, np.float64(0.0)),
 (265, np.float64(0.017609018126512475)),
 (266, np.float64(0.08333333333333333)),
 (267, np.float64(0.08164965809277258)),
 (268, np.float64(0.014664711502135327)),
 (269, np.float64(0.016843038421330378)),
 (270, np.float64(0.22549380840084865)),
 (271, np.float64(0.10327955589886444)),
 (272, np.float64(0.02010075630518424)),
 (273, np.float64(0.010675210253672473)),
 (274, np.float64(0.05985056016645797)),
 (275, np.float64(0.10690449676496974)),
 (276, np.float64(0.037463432463267755)),
 (277, np.float64(0.04140393356054124)),
 (278, np.float64(0.3500700210070024)),
 (279, np.float64(0.1352962850405092)),
 (280, np.float64(0.0)),
 (281, np.float64(0.0408248290463863)),
 (282, np.float64(0.043301270189221926)),
 (283, np.float64(0.0)),
 (284, np.float64(0.013333333333333329)),
 (285, np.float64(0.013801311186847081)),
 (286, np.float64(0.024759378423606912)),
 (287, np.float64(0.030065841120113155)),
 (288, np.float64(0.017609018126512475)),
 (289, np.float64(0.032338083338177726)),
 (290, np.float64(0.03606678538669729)),
 (291, np.float64(0.06810052246069988)),
 (292, np.float64(0.0704360725060499)),
 (293, np.float64(0.017609018126512475)),
 (294, np.float64(0.0759326396601999)),
 (295, np.float64(0.06227991553292183)),
 (296, np.float64(0.035921060405354976)),
 (297, np.float64(0.0611775290321498)),
 (298, np.float64(0.0)),
 (299, np.float64(0.023448415270421966)),
 (300, np.float64(0.33626912299068296)),
 (301, np.float64(0.14026687687393438)),
 (302, np.float64(0.04020151261036848)),
 (303, np.float64(0.016169041669088863)),
 (304, np.float64(0.08336878678455789)),
 (305, np.float64(0.33975790709773834)),
 (306, np.float64(0.1951800145897066)),
 (307, np.float64(0.08848020217749294)),
 (308, np.float64(0.033686076842660756)),
 (309, np.float64(0.04216370213557838)),
 (310, np.float64(0.02970442628930022)),
 (311, np.float64(0.11208970766356098)),
 (312, np.float64(0.10105823052798227)),
 (313, np.float64(0.042884501393511784)),
 (314, np.float64(0.0)),
 (315, np.float64(0.056949479745149925)),
 (316, np.float64(0.044353276257274366)),
 (317, np.float64(0.04364357804719846)),
 (318, np.float64(0.0)),
 (319, np.float64(0.06666666666666665)),
 (320, np.float64(0.1005037815259212)),
 (321, np.float64(0.0)),
 (322, np.float64(0.2585572506271132)),
 (323, np.float64(0.039605901719066965)),
 (324, np.float64(0.016495721976846445)),
 (325, np.float64(0.05619514869490164)),
 (326, np.float64(0.05222329678670935)),
 (327, np.float64(0.03299144395369289)),
 (328, np.float64(0.0)),
 (329, np.float64(0.10565410875907486)),
 (330, np.float64(0.10690449676496976)),
 (331, np.float64(0.041702882811414946)),
 (332, np.float64(0.08247860988423222)),
 (333, np.float64(0.09271726499455303)),
 (334, np.float64(0.1)),
 (335, np.float64(0.06666666666666667)),
 (336, np.float64(0.031139957766460915)),
 (337, np.float64(0.04670993664969137)),
 (338, np.float64(0.039605901719066965)),
 (339, np.float64(0.034815531191139566)),
 (340, np.float64(0.033686076842660756)),
 (341, np.float64(0.07213357077339458)),
 (342, np.float64(0.19157898882855987)),
 (343, np.float64(0.012909944487358055)),
 (344, np.float64(0.018257418583505533)),
 (345, np.float64(0.015430334996209188)),
 (346, np.float64(0.0)),
 (347, np.float64(0.03405026123034994)),
 (348, np.float64(0.04020151261036848)),
 (349, np.float64(0.055470019622522904)),
 (350, np.float64(0.050529115263991134)),
 (351, np.float64(0.0)),
 (352, np.float64(0.01924500897298752)),
 (353, np.float64(0.04200840252084029)),
 (354, np.float64(0.0)),
 (355, np.float64(0.034815531191139566)),
 (356, np.float64(0.05282705437953743)),
 (357, np.float64(0.0)),
 (358, np.float64(0.055470019622522904)),
 (359, np.float64(0.020412414523193145)),
 (360, np.float64(0.07470873676376283)),
 (361, np.float64(0.03333333333333333)),
 (362, np.float64(0.12326312688558731)),
 (363, np.float64(0.11547005383792515)),
 (364, np.float64(0.015032920560056577)),
 (365, np.float64(0.1411300658019085)),
 (366, np.float64(0.06531972647421808)),
 (367, np.float64(0.01632993161855452)),
 (368, np.float64(0.07807200583588264)),
 (369, np.float64(0.04670993664969137)),
 (370, np.float64(0.06885303726590962)),
 (371, np.float64(0.11547005383792511)),
 (372, np.float64(0.06737215368532151)),
 (373, np.float64(0.3829708431025352)),
 (374, np.float64(0.028426762180748053)),
 (375, np.float64(0.057289189923154626)),
 (376, np.float64(0.04364357804719846)),
 (377, np.float64(0.0)),
 (378, np.float64(0.0)),
 (379, np.float64(0.045732956038002356)),
 (380, np.float64(0.015569978883230457)),
 (381, np.float64(0.05298129428260174)),
 (382, np.float64(0.0)),
 (383, np.float64(0.0305887645160749)),
 (384, np.float64(0.03142696805273544)),
 (385, np.float64(0.03903600291794132)),
 (386, np.float64(0.01370377419655063)),
 (387, np.float64(0.014106912317171963)),
 (388, np.float64(0.0)),
 (389, np.float64(0.13862065601673437)),
 (390, np.float64(0.017817416127494958)),
 (391, np.float64(0.07302967433402213)),
 (392, np.float64(0.01702513061517497)),
 (393, np.float64(0.01601281538050871)),
 (394, np.float64(0.014907119849998594)),
 (395, np.float64(0.05443310539518173)),
 (396, np.float64(0.013801311186847081)),
 (397, np.float64(0.03442651863295481)),
 (398, np.float64(0.0)),
 (399, np.float64(0.015430334996209188)),
 (400, np.float64(0.10820035616009185)),
 (401, np.float64(0.15491933384829665)),
 (402, np.float64(0.030860669992418377)),
 (403, np.float64(0.0629940788348712)),
 (404, np.float64(0.10565410875907486)),
 (405, np.float64(0.014322297480788657)),
 (406, np.float64(0.026666666666666658)),
 (407, np.float64(0.0611775290321498)),
 (408, np.float64(0.020739033894608502)),
 (409, np.float64(0.0)),
 (410, np.float64(0.06351073488299556)),
 (411, np.float64(0.04803844614152614)),
 (412, np.float64(0.10613372610104645)),
 (413, np.float64(0.10613372610104645)),
 (414, np.float64(0.01951800145897066)),
 (415, np.float64(0.06298366572977734)),
 (416, np.float64(0.04714045207910316)),
 (417, np.float64(0.03849001794597504)),
 (418, np.float64(0.09630868246861535)),
 (419, np.float64(0.1089898521826132)),
 (420, np.float64(0.11120768749710652)),
 (421, np.float64(0.0)),
 (422, np.float64(0.12060453783110545)),
 (423, np.float64(0.06227991553292183)),
 (424, np.float64(0.025660011963983362)),
 (425, np.float64(0.05100613704506705)),
 (426, np.float64(0.06189844605901728)),
 (427, np.float64(0.01951800145897066)),
 (428, np.float64(0.03380617018914066)),
 (429, np.float64(0.0)),
 (430, np.float64(0.12333396776895567)),
 (431, np.float64(0.01571348402636772)),
 (432, np.float64(0.24731360893412463)),
 (433, np.float64(0.01951800145897066)),
 (434, np.float64(0.0)),
 (435, np.float64(0.02108185106778919)),
 (436, np.float64(0.016843038421330378)),
 (437, np.float64(0.01849000654084097)),
 (438, np.float64(0.035634832254989916)),
 (439, np.float64(0.05345224838248487)),
 (440, np.float64(0.016666666666666666)),
 (441, np.float64(0.036514837167011066)),
 (442, np.float64(0.03802345503146867)),
 (443, np.float64(0.045098761680169734)),
 (444, np.float64(0.013333333333333329)),
 (445, np.float64(0.032338083338177726)),
 (446, np.float64(0.06013168224022631)),
 (447, np.float64(0.015032920560056577)),
 (448, np.float64(0.07580980435789032)),
 (449, np.float64(0.055470019622522904)),
 (450, np.float64(0.030323921743156127)),
 (451, np.float64(0.015569978883230457)),
 (452, np.float64(0.011785113019775792)),
 (453, np.float64(0.01571348402636772)),
 (454, np.float64(0.20207259421636903)),
 (455, np.float64(0.015861031714362882)),
 (456, np.float64(0.1466666666666666)),
 (457, np.float64(0.0547722557505166)),
 (458, np.float64(0.031139957766460915)),
 (459, np.float64(0.0962250448649376)),
 (460, np.float64(0.06885303726590962)),
 (461, np.float64(0.3674234614174766)),
 (462, np.float64(0.09578949441427993)),
 (463, np.float64(0.06221710168382551)),
 (464, np.float64(0.0)),
 (465, np.float64(0.025197631533948477)),
 (466, np.float64(0.1451732372622595)),
 (467, np.float64(0.06227991553292183)),
 (468, np.float64(0.017609018126512475)),
 (469, np.float64(0.06900655593423541)),
 (470, np.float64(0.04803844614152614)),
 (471, np.float64(0.04898979485566356)),
 (472, np.float64(0.06963106238227913)),
 (473, np.float64(0.13645764784420258)),
 (474, np.float64(0.0)),
 (475, np.float64(0.06950480468569158)),
 (476, np.float64(0.08728715609439693)),
 (477, np.float64(0.0)),
 (478, np.float64(0.04642070825485275)),
 (479, np.float64(0.06375767130633381)),
 (480, np.float64(0.1281025230440697)),
 (481, np.float64(0.01632993161855452)),
 (482, np.float64(0.016843038421330378)),
 (483, np.float64(0.1518652793203998)),
 (484, np.float64(0.042884501393511784)),
 (485, np.float64(0.04714045207910316)),
 (486, np.float64(0.03671940368172627)),
 (487, np.float64(0.12649110640673514)),
 (488, np.float64(0.059234887775909226)),
 (489, np.float64(0.0)),
 (490, np.float64(0.1414213562373095)),
 (491, np.float64(0.07794837629539571)),
 (492, np.float64(0.06030226891555272)),
 (493, np.float64(0.024902912254587607)),
 (494, np.float64(0.02108185106778919)),
 (495, np.float64(0.13662601021279464)),
 (496, np.float64(0.028644594961577313)),
 (497, np.float64(0.0)),
 (498, np.float64(0.039605901719066965)),
 (499, np.float64(0.0)),
 (500, np.float64(0.015861031714362882)),
 (501, np.float64(0.047639306734033084)),

In [65]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2405, np.float64(0.4839354795704658)),
 (1533, np.float64(0.43622020338771716)),
 (3160, np.float64(0.4278406467922595)),
 (838, np.float64(0.398216086792002)),
 (4336, np.float64(0.39207842352784267))]

In [66]:
def recommend(movie):
    movie_index=new_df[new_df['title']==movie].index[0]
    distance=similarity[movie_index]
    movies_list=sorted(list(enumerate(distance)),reverse=True,key=lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].title)
        print(i[0])

In [67]:
recommend('Batman Begins')

The Dark Knight
65
The Dark Knight Rises
3
Batman
1360
Batman
1361
Batman & Robin
210

In [68]:
new_df.iloc[2405].title

'Aliens'

In [69]:
import pickle

pickle.dump(new_df, open('movies.pkl', 'wb'))

In [70]:

!pip install joblib

import joblib
joblib.dump(movies,"movies.pkl")

Requirement already satisfied: joblib in C:\Users\ANUSKA BISWAS\miniconda3\Lib\site-packages (1.5.3)

['movies.pkl']

In [71]:
from IPython.display import FileLink
FileLink('movies.pkl')

C:\Users\ANUSKA BISWAS\Machine Learning Projects\Movie Recommander system\movies.pkl

In [72]:
new_df['title'].values

<StringArray>
[                                  'Avatar',
 'Pirates of the Caribbean: At World's End',
                                  'Spectre',
                    'The Dark Knight Rises',
                              'John Carter',
                             'Spider-Man 3',
                                  'Tangled',
                  'Avengers: Age of Ultron',
   'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice',
 ...
                           'On The Downlow',
             'Sanctuary: Quite a Conundrum',
                                     'Bang',
                                   'Primer',
                                   'Cavite',
                              'El Mariachi',
                                'Newlyweds',
                'Signed, Sealed, Delivered',
                         'Shanghai Calling',
                        'My Date with Drew']
Length: 4806, dtype: str

In [74]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [75]:
from IPython.display import FileLink
FileLink('movie_dict.pkl')

C:\Users\ANUSKA BISWAS\Machine Learning Projects\Movie Recommander system\movie_dict.pkl

In [76]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [77]:
from IPython.display import FileLink
FileLink('similarity.pkl')

C:\Users\ANUSKA BISWAS\Machine Learning Projects\Movie Recommander system\similarity.pkl